### ISSUE TITLE
Feedback for deepcell datasets website

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/deepcell-datasets#56]
- 404 error when clicking "Browse Training Data", "Browse Experiments", or "Samples"
- Missing comma in description of password requirements on account creation page
- Missing "special character" as required field for password
- What's the difference between browsing experiments and samples? What will eventually appear on these pages?
- Once logged in, the user is taking to a "data" page that shows the TissueNet dataset. This page isn't linked from the home page anywhere. 
- The "Contribute Data" section doesn't currently do anything: it links to the same Create an Account, Login, and Learn More pages as the top of the website, without anything specifically related to contributing data.

**Comment by willgraf** [comment]
> Once logged in, the user is taking to a "data" page that shows the TissueNet dataset. This page isn't linked from the home page anywhere.

This is by design since the data page shouldn't be accessible without logging in. Do you think it would be better to have a "View the data" button that takes one to a login page?

**Comment by ngreenwald** [comment]
Right, I think the button should be visible, but require the user to be logged in to show the data

**Comment by willgraf** [comment]
Closedy By #57
